Register modal window
olgaX2a/goit-team-project-kapusta-client pull request #23
Opened 2021-11-14 12:35 UTC by tetiana-parkhoniuk

Привіт, Оля) 
Що тут є: 
1) правки після eslint, здається повиправляла свої :) 
2) створила новий компонент RegisterModal для модалки яка відкривається при реєстрації та гайдить користувача на Login. Робила окрему модалку бо shared мені не дуже підійшла для NavLink;
3) Поставила react-toastify та додала нотифікації для auth-operations.
Пиши якщо що :)

2021-11-14 13:08 UTC, olgaX2a reviewed
При вводе неверного пароля нет нотификашки (по крайней мере, я её не вижу).
Окно "Вам отправлено письмо" сейчас отображается вне зависимости от того, какой ответ придёт от сервера (сейчас оно показывается даже если я пробую зарегистрироваться на ту же почту).

2021-11-15 13:34 UTC, olgaX2a requested changes

2021-11-15 13:34 UTC, olgaX2a commented on src/components/RegisterForm/RegisterForm.jsx
> +
тут можно прописать
```
  useEffect(() => {
    showModalIfRegistered();
  }, [isRegistered]);
  ```

2021-11-15 13:34 UTC, olgaX2a commented on src/components/RegisterForm/RegisterForm.jsx
> +      // setTimeout(showModalIfRegistered(isRegistered), 3000);
а это убрать (по сабмиту просто отправляем запрос, не ждём ответов)

2021-11-15 13:53 UTC, tetiana-parkhoniuk commented on src/components/RegisterForm/RegisterForm.jsx
> +
дякую! усьо працює_

2021-11-15 13:54 UTC, tetiana-parkhoniuk commented
Можна мерджити :) 
Дякую за допомогу з RegisterModal - тепер вона відображається коректно) Додала нотифікацію для Invalid Password. Змінила logout з get > post.

2021-11-15 14:00 UTC, olgaX2a approved these changes

2021-11-15 14:00 UTC, merged